[pytest]
addopts = -v -s
testpaths = tests
python_files = test_*.py

markers =
    tc_comp_001: Companies navigation
    tc_comp_002: Companies controls
    tc_comp_003: Plans dropdown
    tc_comp_004: Status dropdown
    tc_comp_005: Types dropdown
    tc_comp_006: Table headers
    tc_comp_007: Export CSV
    add_company: Add company scenarios
    tc_comp_008: Cancel add company
    tc_comp_009: Invalid business rules
    tc_comp_010: Create and delete company
    tc_comp_011: Invalid business rules
    tc_comp_012: Company actions menu options
    tc_comp_013: View company details popup