[pytest]
addopts = -v -s
testpaths = tests
python_files = test_*.py

markers =
    tc_comp_001: Companies navigation
    tc_comp_002: Companies controls
    tc_comp_003: Plans dropdown
    tc_comp_004: Status dropdown
    tc_comp_005: Types dropdown
    tc_comp_006: Table headers
    tc_comp_007: Export CSV
    add_company: Add company scenarios
    tc_comp_008: Cancel add company
    tc_comp_009: Invalid business rules
    tc_comp_010: Create and delete company
    tc_comp_011: Invalid business rules
    tc_comp_012: Company actions menu options
    tc_comp_013: View company details popup
    tc_comp_014: Edit company success test
    tc_comp_015: Validate disable fields are disabled
    tc_comp_016: Edit company name updates successfully
    tc_comp_017: Edit company name duplicate rejected
    tc_comp_018: Suspend and unsuspend company
    tc_comp_019: Verify Search with Non-Existing Company Name
    tc_comp_plan_change: Change company plan
    tc_user_001: Verify All Users Page Navigation
    tc_user_002: Verify All Users Page Controls
    tc_user_003: Verify Breadcrumb Navigation
    tc_user_004: Verify Role Dropdown Values
    tc_user_005: Verify Status Dropdown Values
    tc_user_006: Verify Company Dropdown Loads Companies
    tc_user_007: Verify Users Table Headers
    tc_user_008: Verify Add User Cancel Functionality
    tc_user_009: Verify Add User Required Field Validation
    tc_user_010: Verify Add User Invalid Business Rules
    tc_user_011: Verify Add Company Admin User Successfully
    tc_user_012: Verify Add Employee User Successfully
    tc_user_013: Verify User Status Toggle Visible
    tc_user_014: Verify View User Icon Opens Popup
    tc_user_015: Verify Reset Password Icon Visible
    tc_user_016: Verify Edit User Icon Opens Edit Screen
    tc_user_017: Verify Role Column Displays Valid Role
    tc_user_018: Verify Status Badge Changes when status is changed
    tc_user_019: Verify Export CSV Functionality
    tc_user_020: Verify User Impersonation Functionality
    tc_plans_001: Verify Plans Page Opens
    tc_plans_002: Verify Create Plan Button
    tc_plans_003: Verify Monthly Toggle
    tc_plans_004: Verify Yearly Toggle
    tc_plans_005: Verify Create Plan Page Opens
    tc_plans_006: Verify Cancel Button Returns to Plans 
    tc_plans_007: Verify Mandatory Field Validations
    tc_plans_008: Verify Priority Support Checkbox
    tc_plans_009: Verify Custom Integrations Checkbox
    tc_plans_010: Verify Most Popular Badge Checkbox
    tc_plans_011: Verify Enterprise Checkbox 
    tc_plans_012: Verify Sync Interval Dropdown Visibility Based on Auto-Sync Checkbox
    tc_plans_013: Verify Sync Interval Dropdown Options
    tc_plans_014: Verify Billing Interval dropdown options.
    tc_plans_015: Verify Add Country button opens Country-wise Package form.
    tc_plans_016: Verify Country Dropdown Options
    tc_plans_017: Verify Currency Dropdown Options
    tc_plans_018: Verify Price field accepts valid numeric values
    tc_plans_019: Verify Price Field Accepts Decimal Values
    tc_plans_020: Verify Interval Dropdown Options
    tc_plans_021: Verify Active Checkbox is Checked by Default
    tc_plans_022: Verify user can uncheck the Active checkbox
    tc_plans_023: Verify User Can Delete a Country-wise Package
    tc_plans_024: Create Free Plan Successfully
    tc_plans_025: Create Paid Plan Successfully
    tc_plans_026: Verify Edit Plan Opens
    tc_plans_027: Verify Update Plan Successfully
    tc_plans_028: Verify Updated Details Reflected
    